<a href="https://colab.research.google.com/github/Sennnnto/CSST-101/blob/main/Banda_Exer_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **My First R Program**

Basic Printing

In [ ]:
print ("Hello World")

[1] "Hello World"

Data Type

In [ ]:
myString <- ("Hello World")
num <- 10
floatingnum <- 9.5
isBool <- TRUE

class(myString)
class(num)
class(floatingnum)
class(isBool)

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

Numeric Operation

In [ ]:
x <- 5
y <- 7

sum <- x + y
diff <- x - y
quo <- x / y
mul <- x * y

print(paste0("The sum is ",sum))
print(paste0("The difference is ",diff))
print(paste0("The quotient is ",quo))
print(paste0("The product is ",mul))

cat("\nThe Sum is", sum ,"\n")
cat("The Difference is", diff ,"\n")
cat("The Product is", mul ,"\n")
cat("The Quotient is", quo ,"\n")

[1] "The sum is 12"
[1] "The difference is -2"
[1] "The quotient is 0.714285714285714"
[1] "The product is 35"

The Sum is 12
The Difference is -2
The Product is 35
The Quotient is 0.7142857

User Input

In [ ]:
name = readline("Enter Name: ")
cat(paste0("\nName: ", name, "\n"))

Decision Making

In [ ]:
grade <- 80
if(grade < 75){
  print("Failed")
}else{
  print("Passed")
}

[1] "Passed"

Looping

In [ ]:
for (i in 1:10){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10

Function

In [ ]:
addNumber <- function(a,b){
  return (a+b)
}

addNumber(5,7)

[1] 12

Vectors

In [ ]:
grades <- c(90,88,96,83,91)
grades

mean(grades)
max(grades)
min(grades)
sum(grades)
length(grades)

[1] 90 88 96 83 91

[1] 89.6

[1] 96

[1] 83

[1] 448

[1] 5

Matrices

In [ ]:
A <- matrix(c(1,2,3,4,5,6,7,8),nrow=2)
A

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

Lists

In [ ]:
student <- list(
  Name="Jack",
  Age=9,
  GPA=1.5
)

student

$Name
[1] "Jack"

$Age
[1] 9

$GPA
[1] 1.5

Data Frame

In [ ]:
students <- data.frame(
  Name=c("Jack","Jerome","Sapot"),
  Age=c(12,15,19),
  GPA=c(1.5,1.7,1.99)
)

students
write.csv(students,"Students.csv")

  Name   Age GPA
1 Jack   12  1.50
2 Jerome 15  1.70
3 Sapot  19  1.99

Reading CSV Files

In [ ]:
data <- read.csv("Students.csv")

head(data)

summary(data)

  X Name   Age GPA
1 1 Jack   12  1.50
2 2 Jerome 15  1.70
3 3 Sapot  19  1.99

       X              Name        Age             GPA
 Min.   :1.0   Length   :3   Min.   :12.00   Min.   :1.500
 1st Qu.:1.5   N.unique :3   1st Qu.:13.50   1st Qu.:1.600
 Median :2.0   N.blank  :0   Median :15.00   Median :1.700
 Mean   :2.0   Min.nchar:4   Mean   :15.33   Mean   :1.730
 3rd Qu.:2.5   Max.nchar:6   3rd Qu.:17.00   3rd Qu.:1.845
 Max.   :3.0                 Max.   :19.00   Max.   :1.990